apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1vhk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1vhk
    app.kubernetes.io/part-of: cin4s-839-0095-app
  name: devfile-sample-1vhk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1vhk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1vhk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0095-tenant/cin4s-839-0095-app/devfile-sample-1vhk@sha256:bc5b355f43fbf51643d24f6e5ce24fedd4f95c55f95ae45e5189fe18849ae9ee
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
